package com.crosscert.passkey.audit.domain;

public enum AuditEventType {
  TENANT_CREATED,
  API_KEY_ISSUED,
  API_KEY_REVOKED,
  CREDENTIAL_REGISTERED,
  CREDENTIAL_AUTHENTICATED,
  CREDENTIAL_REVOKED,
  CREDENTIAL_RENAMED,
  SIGNATURE_COUNTER_REGRESSION,
  ATTESTATION_TRUST_FAILED
}
